### ISSUE TITLE
timetemp.py requires packages not installed in the Tutorial

### ISSUE THREAD

**Issue by mitchmitchell** [adafruit/Python-Thermal-Printer#24]
The Tutorial needs to be updated to include installing all the packages required by timetemp.py -- currently errors out trying to load the Image module.

**Comment by mitchmitchell** [comment]
Traceback (most recent call last):
  File "timetemp.py", line 18, in <module>
    import Image, ImageDraw, time, urllib, json
ImportError: No module named Image

**Comment by mitchmitchell** [comment]
Changing the import lines to the following fixed the problem:

**Comment by mitchmitchell** [comment]
sudoku-gfx.py  has the same issue

**Comment by PaintYourDragon** [comment]
Thanks for spotting that. Just pushed corrected code to the repo.

**Comment by mitchmitchell** [comment]
main.py has the same issue as well...
