### ISSUE TITLE
API Documentation URL for Twitter is incorrect

### ISSUE THREAD

**Issue by icberg7** [adafruit/Python-Thermal-Printer#25]
https://github.com/adafruit/Python-Thermal-Printer/blob/master/twitter.py#L42 indicates that the correct page to view documentation on twitter search is http://dev.twitter.com/docs/using-search; however, that page returns a 404.
It looks like Twitter has redone their API documentation site and the correct link should be: https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets

**Comment by sauntheninja2** [comment]
Has this issue been solved?

**Comment by ladyada** [comment]
it has now :)
