### ISSUE TITLE
Weird characters

### ISSUE THREAD

**Issue by PierreTrp** [adafruit/Python-Thermal-Printer#31]
When i run `./printertest.py`, i get weird characters printed

![img_4225](https://user-images.githubusercontent.com/3466281/48271369-795b5700-e43c-11e8-984d-d5e24f69842a.JPG)

any ideas why?

**Comment by ladyada** [comment]
could be wrong baud rate, you want 9600. if you purchased from adafruit & need more tech support please post to the forums :)

**Comment by PierreTrp** [comment]
it was indeed the baudrate. I tried before with 9600 and it was not working, but not it is. Thanks
