### ISSUE TITLE
Error running "main.py"

### ISSUE THREAD

**Issue by mattpackwood** [adafruit/Python-Thermal-Printer#53]
Hi, I am getting the following...

```
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    printer.printImage(Image.open('gfx/hello.png'), True)
  File "/home/pi/Python-Thermal-Printer/Adafruit_Thermal.py", line 552, in printImage
    image = Image.open(image_file)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2643, in open
    prefix = fp.read(16)
AttributeError: 'PngImageFile' object has no attribute 'read'
```

Matt

**Comment by cefoster0** [comment]
I'm getting the same error

**Comment by abetusk** [comment]
I was getting the same error. The error comes from the function `printer.printImage` needing a filename (string) **not** an image file (see [here](https://github.com/adafruit/Python-Thermal-Printer/blob/master/Adafruit_Thermal.py#L550)). Changing [line 101 in `main.py`](https://github.com/adafruit/Python-Thermal-Printer/blob/master/main.py#L101) to:

```python3
# Print greeting image
printer.printImage('gfx/hello.png', True)
printer.feed(3)
GPIO.output(ledPin, GPIO.LOW)
```

should get past this hurdle, though there might be other problems lurking (I haven't tried running the full project or `main.py`).

Note that the other call to `printImage` in `main.py` ([line 43](https://github.com/adafruit/Python-Thermal-Printer/blob/master/main.py#L43)) will also need to be changed. Presumably the `sudoku-gfx.py` file has similar errors in it as well. I'm giving up on chasing all the bugs but I would bet every script in this project that tried to print a PNG file will now stop working.

I would guess that someone introduced breaking changes to the and this is what broke all the scripts in this project. From a cursory look, it seems like the breaking change was [here](https://github.com/adafruit/Python-Thermal-Printer/commit/fc3933677a885ac3a5e4d4165bcd6fb3941ea727#diff-630bb7a9ab6a85ca279ddaf93009df9f2f35a973a948e8104490c9d1c511d343) by @galacticfan on May 20, 202.

**Comment by CodeDelux** [comment]
Abetusk,  I don't think this will work because there are other calls to that function requiring the Image.new.  We had to change Adafruit_Thermal.py to get this to work correctly.

Unfortunately, we are new to GitHub and still trying to figure out how to propose our changes :).

**Comment by CodeDelux** [comment]
Just added a pull request labeled "Add files via upload" with our fixed code.

**Comment by PaintYourDragon** [comment]
Merged. Thank you muchly!

**Comment by mattpackwood** [comment]
@CodeDelux 

I tried running` python3 main.py` and I get:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyS0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 22, in <module>
    from datetime import date
  File "/home/pi/Python-Thermal-Printer/datetime.py", line 16, in <module>
    printer = Adafruit_Thermal("/dev/ttyS0", 19200, timeout=5)
  File "/home/pi/Python-Thermal-Printer/Adafruit_Thermal.py", line 84, in __init__
    Serial.__init__(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyS0: [Errno 2] No such file or directory: '/dev/ttyS0
```'

**Comment by CodeDelux** [comment]
We only use the built in python datetime and we don’t have a local version. So, I think @abetusk is right and you should rename it.

**Comment by mattpackwood** [comment]
OK, I think that is "all set", I agree there is something "up" with `datetime.py` I don't know how to put in a pull request to "delete a file" so I will put in a new issue,
